### ISSUE TITLE
Every bidict creates a reference cycle

### ISSUE THREAD

**Issue by lordmauve** [jab/bidict#24] opened 2015-11-25 20:51 UTC
The fact that every bidict creates an holds a reference to its inverse bidict, and each inverse holds a reference to the forward bidict, means that bidicts will create reference cycles.

This has two implications:
1. Memory won't be reclaimed immediately if the references are deleted. They will be reclaimed by the garbage collector - but at some later point. Large bidicts could therefore hold memory much longer than a standard dict.
2. Prior to Python 3.4, any subclasses of bidict that happen to implement `__del__()` methods won't be garbage collectable at all.

I'm not sure how important this is, but it's more important the less you know about ways in which bidict is used.

A workaround might be not to hold a full reference to inv, but to instead hold a weak memoized reference. This would guarantee

```
d.inv.inv is d
```

but would allow immediate reclamation of either side of the bidict pair if no reference to them are held.

**Comment by jab** [comment] 2015-11-25 21:19
Thanks for opening this. I explored this in #3 but just ended up documenting the current behavior (though missed the point about `__del__`, thanks for noting). Great to have an opportunity to discuss this with a potential user. Are there any downsides to going ahead with this?

**Comment by lordmauve** [comment] 2015-11-25 23:10
The downside is performance. ``d.inv`` would need to check a weakref.ref and recreate an instance if it doesn't exist. So a loop like

    [d.inv[v] for v in vs]

could be much slower.

Alternatively, we could lazily create one direction of references so that

    d.inv.inv is not d

but at least

    d.inv is d.inv

There might be a performant way to implement the current semantics in C. Or that might be a nasty hack.

**Comment by jab** [comment] 2015-11-27 15:23
Thanks for the ideas and explanation. Since there's a tradeoff with every approach, it would be premature optimization to choose one of these before ever actually encountering a situation where this is a problem and where we could test which proposal works best. Would you like to create a synthetic example simulating where you'd expect to hit this in a real application, where we can experiment further, or should I close for now and reopen if it ever comes up in a real application?

**Comment by jab** [comment] 2015-12-20 03:02
I'm going to close this for now, and we can reopen if anyone ever encounters a performance issue caused by this.

**Comment by jab** [comment] 2017-11-27 16:18
Hi @lordmauve, I'm experimenting with a weakref implementation in #47. I confirmed that after allocating a bidict `b` and then running `del b`, some memory is now immediately reclaimed.

Here is a baseline:
```
Python 3.6.3 (default, Oct  4 2017, 06:09:15)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import ipython_memory_usage.ipython_memory_usage

In [2]: ipython_memory_usage.ipython_memory_usage.start_watching_memory()
In [2] used 2.5586 MiB RAM in 14.63s, peaked 0.00 MiB above current, total RAM usage 42.66 MiB

In [3]: class MyDict(dict): pass
In [3] used 0.0312 MiB RAM in 0.11s, peaked 0.00 MiB above current, total RAM usage 42.70 MiB

In [4]: d = MyDict((i, i) for i in range(10**5))
In [4] used 11.5273 MiB RAM in 0.12s, peaked 0.00 MiB above current, total RAM usage 54.22 MiB

In [5]: del d
In [5] used -2.5000 MiB RAM in 0.11s, peaked 2.50 MiB above current, total RAM usage 51.72 MiB

In [6]: d = MyDict((i, i) for i in range(10**5))
In [6] used 2.4766 MiB RAM in 0.12s, peaked 0.00 MiB above current, total RAM usage 54.20 MiB

In [7]: del d
In [7] used -2.2461 MiB RAM in 0.11s, peaked 2.25 MiB above current, total RAM usage 51.95 MiB
```

As expected, with the latest (0.14.0) release where `b` and `b.inv` create a reference cycle, when `b`’s  refcount drops to 0, memory is not immediately reclaimed:
```
In [9]: import bidict
In [9] used -0.0859 MiB RAM in 0.11s, peaked 0.00 MiB above current, total RAM usage 51.87 MiB

In [10]: bidict.__version__
Out[10]: '0.14.0'
In [10] used 0.0117 MiB RAM in 0.10s, peaked 0.00 MiB above current, total RAM usage 51.88 MiB

In [11]: b = bidict.bidict((i, i) for i in range(10**5))
In [11] used 17.8906 MiB RAM in 0.35s, peaked 0.00 MiB above current, total RAM usage 69.78 MiB

In [12]: del b
In [12] used 0.0000 MiB RAM in 0.11s, peaked 0.00 MiB above current, total RAM usage 69.78 MiB

In [13]: b = bidict.bidict((i, i) for i in range(10**5))
In [13] used 15.4375 MiB RAM in 0.34s, peaked 0.76 MiB above current, total RAM usage 85.22 MiB

In [14]: del b
In [14] used 0.0039 MiB RAM in 0.10s, peaked 0.00 MiB above current, total RAM usage 85.22 MiB

In [15]: b = bidict.bidict((i, i) for i in range(10**5))
In [15] used 0.0664 MiB RAM in 0.33s, peaked 0.83 MiB above current, total RAM usage 85.29 MiB

In [16]: del b.inv
In [16] used 0.0000 MiB RAM in 0.10s, peaked 0.00 MiB above current, total RAM usage 85.29 MiB

In [17]: del b
In [17] used -11.0000 MiB RAM in 0.11s, peaked 11.00 MiB above current, total RAM usage 74.29 MiB

In [18]: b = bidict.bidict((i, i) for i in range(10**5))
In [18] used 8.3359 MiB RAM in 0.32s, peaked 0.00 MiB above current, total RAM usage 82.62 MiB

In [19]: del b.inv
In [19] used 0.0000 MiB RAM in 0.11s, peaked 0.00 MiB above current, total RAM usage 82.62 MiB

In [20]: del b
In [20] used -10.7500 MiB RAM in 0.11s, peaked 10.75 MiB above current, total RAM usage 71.88 MiB
```

(This also shows that if you first manually run `del b.inv`, then memory is immediately reclaimed when `b`’s refcount drops to 0.)

With the "weakrefinv" branch from #47, now memory is immediately reclaimed when `b`’s refcount drops to 0, with no need to manually run `del b.inv` first:

```
In [5]: b = bidict.bidict((i, i) for i in range(10**5))
In [5] used 20.9180 MiB RAM in 0.36s, peaked 0.00 MiB above current, total RAM usage 64.81 MiB

In [6]: del b
In [6] used -2.2383 MiB RAM in 0.10s, peaked 2.25 MiB above current, total RAM usage 62.57 MiB
```

I just need to get things working on Python 2, add some missing docstrings, and get the changes reviewed before I land them. Since you opened this issue, would you be willing to review the changes in #47? Thanks! 😊

**Closed** 2017-12-07 18:16 UTC

**Comment by jab** [comment] 2017-12-17 21:38
@lordmauve wrote:

> The downside is performance. d.inv would need to check a weakref.ref and recreate an instance if it doesn't exist. So a loop like [d.inv[v] for v in vs] could be much slower.

With my [latest changes in master](https://github.com/jab/bidict/blob/f4fc9f5/bidict/_frozen.py#L135-L145), this is now exactly what I'm doing.

<details><summary>(click to view)</summary>

```python
    @property
    def inv(self):
        """The inverse of this bidict."""
        if self._inv is not None:
            return self._inv
        inv = self._invref()  # pylint: disable=E1102
        if inv is not None:
            return inv
        # Refcount of referent must have dropped to zero, as in `bidict().inv.inv`. Init a new one.
        self._init_inv()
        return self._inv
```

</details>

If anyone is doing something like `[b.inv[v] for v in vs]` and actually experiences an unacceptable performance hit from the added logic in the `.inv` call, they could just pull the `b.inv` call outside the loop:

```python
inv = b.inv
[inv[v] for v in vs]
```

Given that this is still hypothetical I'm not sure it's worth adding a caveat about this to the docs, but I have added a link to this issue from the changelog entry where I noted the resolution of this issue. Please let me know if you have any further thoughts.

**Comment by jab** [comment] 2017-12-17 21:48
@lordmauve I just [added a test](https://github.com/jab/bidict/commit/cecb6ebe5dfbb92193f9620a68dbea0394d1a00f#diff-47b0be0e516ff5ea6a7c729ead8a8e0bR165) to verify that a bidict's refcount does in fact drop to zero after you have no more references to it.

<details><summary>(click to view)</summary>

```python
@pytest.mark.skipif(PYPY, reason='On PyPy the refcount is still 2')
@pytest.mark.parametrize('B', bidict_types)
def test_no_reference_cycles(B):
    def refcount():
        return len(get_referrers(B()))
    assert refcount() == 0
```

</details><br>

With bidict 0.14.2, these tests would fail because of the reference cycle (the refcount would be 2, not 0). Testing against latest master with CPython, the tests pass.

However, on PyPy the refcount still comes out as 2, even with using weakrefs in one direction. Do you have any idea what's going on here? Is there still a reference cycle somehow on PyPy? Is the problem just with the way I'm testing this? Thanks in advance for any insights!

**Comment by lordmauve** [comment] 2017-12-17 23:39
I don't completely see how the test is intended to work. You're just trying to check the refcount for a bidict instance? I don't see why you would expect it to be zero though. The refcount will never be zero for a live object.

You could just compare sys.getrefcount(B()) - this will be 1 if the only reference is the one passed in, and 2 if bidict instances also hold themselves alive.

I think a more convincing test, if it works, might be to test whether the object relies on the GC to destroy it. You could disable GC (gc.disable()), then create a weakref to a bidict and throw away all hard references. If the object is relying on GC for destruction (because there are ref cycles) then it will still be accessible through the weakref. If it's purely refcounted it will have been destroyed.

**Comment by jab** [comment] 2017-12-18 02:48
Thanks for taking a look, @lordmauve.

> You could just compare sys.getrefcount(B()) - this will be 1 if the only reference is the one passed in, and 2 if bidict instances also hold themselves alive.

That's actually the first thing I tried, but in PyPy, `from sys import getrefcount` raises `ImportError`.

> I don't see why you would expect it to be zero though. The refcount will never be zero for a live object.

That's what I tried initially, but when I tested, I was getting back 0 with the weakref changes. What are we missing?

> I think a more convincing test, if it works...

I like that better too, thanks for the suggestion. Done in a576bf33e53cb4877428fd3a237ae7d9b684f2f2. Let me know if that looks like what you had in mind.

Interestingly though, that test still doesn't pass on PyPy. I reread [these PyPy docs](http://doc.pypy.org/en/latest/cpython_differences.html#differences-related-to-garbage-collection-strategies) and realized this is probably expected behavior ("It also means that weak references may stay alive for a bit longer than expected"). So I'll just leave the `@pytest.mark.skipif(PYPY...)` in place and call this done.

I'm psyched to do a new release including these changes sometime soon. It's been a minute though since bidict got a proper code review. Would you be interested in taking a fresh look at the latest code sometime and letting me know if it still LGTY?

**Comment by lordmauve** [comment] 2017-12-18 09:59
Oh, right. PyPy is always GCed so you don't need to care about it at all here.
