### ISSUE TITLE
0.22.1: temp directory in source tree trashes build

### ISSUE THREAD

**Issue by kloczek** [jab/bidict#307] opened 2024-02-11 19:43 UTC
Looks like some gits are missing in pyprojxt.toml because additional directory trashes build.
<details>
<summary>Here is example</summary>

```console
+ mkdir temp
+ /usr/bin/python3 -sBm build -w --no-isolation
* Getting build dependencies for wheel...
No `name` configuration, performing automatic discovery
No `packages` or `py_modules` configuration, performing automatic discovery.
`flat-layout` detected -- analysing .
discovered packages -- ['bidict', 'temp']
No `name` configuration, performing automatic discovery
No parent package detected, impossible to derive `name`
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
  File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
    self.run_setup()
  File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 311, in run_setup
    exec(code, locals())
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 159, in setup
    dist.parse_config_files()
  File "/usr/lib/python3.8/site-packages/setuptools/dist.py", line 623, in parse_config_files
    setupcfg.parse_configuration(
  File "/usr/lib/python3.8/site-packages/setuptools/config/setupcfg.py", line 189, in parse_configuration
    meta.parse()
  File "/usr/lib/python3.8/site-packages/setuptools/config/setupcfg.py", line 500, in parse
    section_parser_method(section_options)
  File "/usr/lib/python3.8/site-packages/setuptools/config/setupcfg.py", line 475, in parse_section
    self[name] = value
  File "/usr/lib/python3.8/site-packages/setuptools/config/setupcfg.py", line 293, in __setitem__
    parsed = self.parsers.get(option_name, lambda x: x)(value)
  File "/usr/lib/python3.8/site-packages/setuptools/config/setupcfg.py", line 592, in _parse_version
    return expand.version(self._parse_attr(value, self.package_dir, self.root_dir))
  File "/usr/lib/python3.8/site-packages/setuptools/config/setupcfg.py", line 416, in _parse_attr
    package_dir.update(self.ensure_discovered.package_dir)
  File "/usr/lib64/python3.8/_collections_abc.py", line 720, in __iter__
    yield from self._mapping
  File "/usr/lib/python3.8/site-packages/setuptools/config/expand.py", line 462, in __iter__
    return iter(self._target())
  File "/usr/lib/python3.8/site-packages/setuptools/config/expand.py", line 452, in _target
    self._value = self._obtain()
  File "/usr/lib/python3.8/site-packages/setuptools/config/expand.py", line 422, in _get_package_dir
    self()
  File "/usr/lib/python3.8/site-packages/setuptools/config/expand.py", line 412, in __call__
    self._dist.set_defaults(name=False)  # Skip name, we can still be parsing
  File "/usr/lib/python3.8/site-packages/setuptools/discovery.py", line 353, in __call__
    self._analyse_package_layout(ignore_ext_modules)
  File "/usr/lib/python3.8/site-packages/setuptools/discovery.py", line 387, in _analyse_package_layout
    or self._analyse_flat_layout()
  File "/usr/lib/python3.8/site-packages/setuptools/discovery.py", line 444, in _analyse_flat_layout
    return self._analyse_flat_packages() or self._analyse_flat_modules()
  File "/usr/lib/python3.8/site-packages/setuptools/discovery.py", line 450, in _analyse_flat_packages
    self._ensure_no_accidental_inclusion(top_level, "packages")
  File "/usr/lib/python3.8/site-packages/setuptools/discovery.py", line 480, in _ensure_no_accidental_inclusion
    raise PackageDiscoveryError(cleandoc(msg))
setuptools.errors.PackageDiscoveryError: Multiple top-level packages discovered in a flat-layout: ['bidict', 'temp'].

To avoid accidental inclusion of unwanted files or directories,
setuptools will not proceed with this build.

If you are trying to create a single distribution with multiple packages
on purpose, you should not rely on automatic discovery.
Instead, consider the following options:

1. set up custom discovery (`find` directive with `include` or `exclude`)
2. use a `src-layout`
3. explicitly set `py_modules` or `packages` with a list of names

To find more information, look for "package discovery" on setuptools docs.

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_wheel
```
</details>

**Comment by jab** [comment] 2024-02-12 01:54
I can't reproduce this.

Your output includes the following:
> No `packages` or `py_modules` configuration, performing automatic discovery.

which is not supposed to happen.

You can see that pyproject.toml sets `packages` [here](https://github.com/jab/bidict/blob/ca4a9bd5e0977363a9ca614f3354bfb442eca41f/pyproject.toml#L43). So there is no need to fall back to automatic discovery.

Sorry I have no idea why it's behaving as if `packages` is not set when you run it.

Closing this as likely invalid, but please reopen if I've missed something.

**Closed by jab** 2024-02-12 01:54 UTC

**Comment by kloczek** [comment] 2024-02-12 15:19
Did you try to reproduce that? 🤔

**Comment by jab** [comment] 2024-02-12 15:52
Yes. (I wouldn't have said "I can't reproduce this" if I hadn't tried to.) I ran `mkdir temp` and then the exact same `build` command that you pasted above, and the package built successfully. I tried making the temp dir in both the root of the clone as well as the "bidict" subdir and both succeeded. As I mentioned, the output you shared seems consistent with using some modified version of my pyproject.toml which doesn't set `packages` or `py_modules`.

**Comment by kloczek** [comment] 2024-02-12 21:34
<details>
<summary>List of installed modules in build env in which found that issue</summary>

```console
Package                       Version
----------------------------- --------
alabaster                     0.7.16
attrs                         23.2.0
Babel                         2.14.0
build                         1.0.3
charset-normalizer            3.3.2
cppclean                      0.13
distro                        1.9.0
dnf                           4.19.0
docutils                      0.20.1
exceptiongroup                1.1.3
gpg                           1.23.2
hypothesis                    6.84.3
idna                          3.6
imagesize                     1.4.1
importlib_metadata            7.0.1
iniconfig                     2.0.0
installer                     0.7.0
Jinja2                        3.1.3
libdnf                        0.73.0
MarkupSafe                    2.1.3
packaging                     23.2
pluggy                        1.3.0
py-cpuinfo                    9.0.0
Pygments                      2.17.2
pyproject_hooks               1.0.0
pytest                        8.0.0
pytest-benchmark              4.0.0
python-dateutil               2.8.2
pytz                          2024.1
requests                      2.31.0
setuptools                    69.1.0
six                           1.16.0
snowballstemmer               2.2.0
sortedcontainers              2.4.0
Sphinx                        7.1.2
sphinx-copybutton             0.5.2
sphinxcontrib-applehelp       1.0.4
sphinxcontrib-devhelp         1.0.5
sphinxcontrib-htmlhelp        2.0.5
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.7
sphinxcontrib-serializinghtml 1.1.10
tomli                         2.0.1
urllib3                       1.26.18
wheel                         0.42.0
zipp                          3.17.0
```
</details>

Here is fix of similar issue in other python module
https://github.com/tsutsu3/uc.micro-py/commit/67e366ea

**Comment by jab** [comment] 2024-02-16 02:49
If you can provide a PR or at least a minimal repro that isolates the issue to something in bidict, I can look into this further.

**Comment by jab** [comment] 2024-02-16 02:50
For example, a bash script anyone can run locally that clones the repo, creates the temp dir, and tries to build the package.
